server:
  port: 8080
spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/products/**
  level:
    org.springframework.cloud.gateway: DEBUG
