server:
  port: 8080
spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/products/**
            - id: user-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/users/**
            - id: cart-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/carts/**
  logging:    
  level:
    org.springframework.cloud.gateway: DEBUG
