server:
  port: 8080
spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/products/**
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
            - id: cart-service
              uri: lb://cart-service
              predicates:
                - Path=/api/carts/**
  