server:
  port: 8080
spring:
  cloud:
    gateway:
      webmvc:
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        routes:
          - id: product-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/products/**
  level:
    org.springframework.cloud.gateway: DEBUG
